---
title: "EpiModel Development Results"
author: "Shawnee M. Anderson"
date: "January 24, 2020"
output:
  html_document:
    df_print: paged
  word_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
library(knitr)
library(MASS)
library(ggplot2)
opts_chunk$set(echo=FALSE,
               cache=TRUE, autodep=TRUE, cache.comments=FALSE,
               message=FALSE, warning=FALSE)
knitr::opts_knit$set(root.dir = "C:/Users/smande6/Box Sync/PAF-Guidelines/Master")
xtick<-c(3121, 3200, 3300, 3400, 3500, 3600)
```

Simulation results of 

## Baseline Simulation

```{r echo = TRUE, eval = TRUE}
load("sim.n7001.rda")
plot(sim, y = "test.past.year", main = "Overall Tests Past Year")
plot(sim, y = "test.gc.12mo", main = "GC: Overall Tests Past Year")
plot(sim, y = "ir100.gc", main = "GC Incidence")
plot(sim, y = "test.ct.12mo", main = "CT: Overall Tests Past Year")
plot(sim, y = "ir100.ct", main = "CT Incidence")
plot(sim, y = "i.prev.dx", main = "HIV Prevalence")
```

```{r echo = FALSE, eval = TRUE}
df <- as.data.frame(sim, out = "mean")
mean <- c(mean(tail(df$test.past.year, 52)),
          mean(tail(df$test.gc.12mo, 52)),
          mean(tail(df$ir100.gc, 52)),
          mean(tail(df$test.ct.12mo, 52)),
          mean(tail(df$ir100.ct, 52)),
          mean(tail(df$i.prev.dx, 52)))
kable(mean, caption = "Statistics: Final Year of Simulation")
```


                    